export const SubscriptionError = {
  CREDIT_INSUFFICIENT: 'CREDIT_INSUFFICIENT',
  SUBSCRIPTION_ACTIVE_EXISTS: 'SUBSCRIPTION_ACTIVE_EXISTS',
  SUBSCRIPTION_NOT_ACTIVE: 'SUBSCRIPTION_NOT_ACTIVE',
  UPGRADE_INVALID_TIER: 'UPGRADE_INVALID_TIER',
  SUBSCRIPTION_STATUS_INVALID: 'SUBSCRIPTION_STATUS_INVALID',
  SUBSCRIPTION_FEATURE_DISABLED: 'SUBSCRIPTION_FEATURE_DISABLED',
  GRANT_NO_ACTIVE_SUB: 'GRANT_NO_ACTIVE_SUB',
  STATE_MACHINE_TERMINAL: 'STATE_MACHINE_TERMINAL',
} as const;

export type SubscriptionErrorCode = (typeof SubscriptionError)[keyof typeof SubscriptionError];
